export const case0 = {
    stationTitle: "Margaret Smith",
    stemText: "Margaret Smith is a 55 year old lady who has come in with a headache.",
    patient: [
        "Where: one side, unilateral, at the back of the head",
        "When: one hour ago, recently",
        "quality: distressing thunderclap",
        "quantity, rate out of 10, severity: 10/10, worst in my life",
        "alleviating (relieving, better): none",
        "aggravating (exacerbating, worse): lights, photophobic, photophobia",
        "beliefs: none",
        "concerns: am I going to die?",
        "mother had autosomal polycystic kidney disease (renal disease, adpkd)",
        "family history/family hx: I'm not sure but if you specified some things...",
        "nausea",
        "vomiting",
        "neck stiff (neck stiffness)",
        "diplopia",
        "high blood pressure (hypertension, HTN), 150/80 today",
        "lost consciousness (loss of consciousness, loc) momentarily at start",
        "confused (confusion)",
        "smoke cigarettes 10 packs per day for past 20 years (smoked, smoking)",
        "occupation: primary school teacher",
        "eye movement/movements on looking to the left: left eye does not abduct"
    ],
    options: {
        Migraine: "pikachu",
        "Tension-type headache": "bulbasaur",
        "Cluster headache": "charmander",
        Meningitis: "squirtle",
        "Subarachnoid haemorrhage": "golem",
        "Epidural haemorrhage": "zubat",
        "Subdural haemorrhage": "pidgey",
        "Temporal arteritis": "spearow",
        "Idiopathic intracranial hypertension": "grimer",
        "Medication-overuse headache": "koffing",
        "Brain tumour": "ekans",
        "Carotid dissection": "meowth",
        Sinusitis: "eevee",
        Encephalitis: "porygon"
    },
    numHitsRequired: 12
}

export const case1 = {
    stationTitle: "John Jameson",
    stemText: "John Jameson is a 35 year old man who has come to discuss his headaches.",
    patient: [
  "where: one side, unilateral, at the front behind the eye",
  "when: happened 2:00am today, gone now",
  "rapid onset peaking within minutes",
  "two hours duration",
  "has happened before, usually around 2:00am every day for several years",
  "quality: excruciating, sharp, piercing, pulsating",
  "quantity, rate out of 10, severity: 10/10, worst in my life, has made me want to end it all sometimes",
  "alleviating (relieving, better): banging my head on the wall and pacing back and forth",
    "aggravating (exacerbating, worse): lights, photophobic, photophobia",
  "triggers/triggered by alcohol sometimes",
  "past medical history (past history) of trauma/concussion in football game five years back",
  "beliefs: I think I get really bad migraines",
  "concerns: Doc, if it goes on any longer, I'm going to off myself. It's that bad!",
  "family: I'm not sure",
  "nausea",
  "vomiting",
  "drinking/alcohol: 2 standard drinks a day, sometimes I go out binge drinking at parties though",
  "smoke cigarettes 10 packs per day for past 20 years (smoked, smoking)",
  "lacrimation, runny eyes, crying, teary",
  "rhinorrhoea, runny nose",
  "occupation: truck driver",
  "autonomic: be specific.",
  "nasal congestion, stuffy nose"
],
    options: {
        Migraine: "harry",
        "Tension-type headache": "ron",
        "Cluster headache": "hermione",
        Meningitis: "dumbledore",
        "Subarachnoid haemorrhage": "snape",
        "Epidural haemorrhage": "lupin",
        "Subdural haemorrhage": "sirius",
        "Temporal arteritis": "voldemort",
        "Idiopathic intracranial hypertension": "malfoy",
        "Medication-overuse headache": "dobby",
        "Brain tumour": "umbridge",
        "Carotid dissection": "fred",
        Sinusitis: "george",
        Encephalitis: "percy"
    },
    numHitsRequired: 10
}

export const case2 = {
    stationTitle: "Gertrud de Smit",
    stemText: "Gertrud de Smit is a 62 year old woman who has come with a headache.",
    patient: [
        "where: unilateral, near temple on right side",
        "when: five hours ago",
        "has not happened before in the past",
        "quality: pulsating",
        "quantity, rate out of 10, severity: 7/10",
        "alleviating (relieving, better): none",
        "aggravating (exacerbating, worse): seems tender on touching my scalp/scalp tenderness",
        "past medical history (past history): not sure but if you ask me specifically...",
        "ischaemic heart disease / heart attack / myocardial infarction / acute coronary syndrome / stemi",
        "shoulder pain / pain in shoulders",
        "beliefs: not sure",
        "low-grade fever / temperature",
        "concerns: I just want it to get better",
        "visual changes/vision: noticed that I can't seem to see as much on my right eye",
        "jaw claudication: pain on chewing",
        "family: mom was from the Netherlands",
        "smoke cigarettes 10 packs per day for past 20 years (smoked, smoking)",
        "temporal artery absent pulse",
        "funduscopy / ophthalmoscopy: pallor and oedema of optic disc"
    ],
    options: {
        Migraine: "valjean",
        "Tension-type headache": "fantine",
        "Cluster headache": "cosette",
        Meningitis: "marius",
        "Subarachnoid haemorrhage": "eponine",
        "Epidural haemorrhage": "thenadier",
        "Subdural haemorrhage": "azelma",
        "Temporal arteritis": "javert",
        "Idiopathic intracranial hypertension": "enjolras",
        "Medication-overuse headache": "gavroche",
        "Brain tumour": "myriel",
        "Carotid dissection": "grantaire",
        Sinusitis: "combeferre",
        Encephalitis: "courfeyrac"
    },
    numHitsRequired: 10,
}

export const case3 = {
    stationTitle: "Zhang Wen",
    stemText: "Zhang Wen is a 67 year old man who has come in with a headache.",
    patient: [
  "Sort of all over the head, but hard to localise (where)",
  "when: two days ago",
  "has not happened before",
  "quality: excruciating, sharp, piercing, pulsating",
  "quantity, rate out of 10, severity: 7/10",
  "alleviating (relieving, better): nothing",
  "aggravating (exacerbating, worse): lights, photophobic, photophobia",
  "past medical history (past history) of ITP, high blood pressure / hypertension",
  "asplenia / splenectomy / spleen removed",
  "beliefs: I think I have the flu",
  "concerns: Is it contagious?",
  "fever / temperature / 38.2 celsius / febrile",
  "sick contacts: my baby daughter was sick last week, I don't know with what though",
  "I was born in China, I do not know my immunisations / vaccination / vaccines / immunised",
  "family: father had high blood pressure",
  "petechial rash on trunk",
  "nausea",
    "vomiting",
    "neck stiff (neck stiffness)",
  "kernig sign positive",
  "brudzinski sign positive",
  "very tired/lethargic/confused/confusion/altered mental status",
  "live in crowded house with extended family"
],
    options: {
        Migraine: "aang",
        "Tension-type headache": "zuko",
        "Cluster headache": "katara",
        Meningitis: "sokka",
        "Subarachnoid haemorrhage": "iroh",
        "Epidural haemorrhage": "azula",
        "Subdural haemorrhage": "toph",
        "Temporal arteritis": "kuvira",
        "Idiopathic intracranial hypertension": "korra",
        "Medication-overuse headache": "mako",
        "Brain tumour": "bolin",
        "Carotid dissection": "asami",
        Sinusitis: "tenzin",
        Encephalitis: "zaheer"
    },
    numHitsRequired: 12
}
